import React from 'react';
import { Award, Trophy } from 'lucide-react';

const Achievements: React.FC = () => {
  const achievements = [
    {
      title: 'All Girls\' Best Team, Div-2',
      event: 'BRACU Intra Programming Contest',
      year: 'Fall 2022',
      description: 'Recognized as the best all-girls team in Division 2 at BRAC University\'s internal programming contest.',
      icon: <Trophy size={32} style={{ color: '#f39c12' }} />
    },
    {
      title: 'Open Source Contributor',
      event: 'LF Connectivity - Meta Projects',
      year: '2025',
      description: 'Active contributor to Maveric and ISPToolbox projects under the Linux Foundation Connectivity initiative.',
      icon: <Award size={32} style={{ color: '#3498db' }} />
    },
    {
      title: 'Undergraduate Thesis',
      event: 'GAN-Based Medical Image Synthesis',
      year: '2025',
      description: 'Research on enhancing deep learning diagnosis of rare diseases using synthetic medical images generated by GANs.',
      icon: <Award size={32} style={{ color: '#27ae60' }} />
    }
  ];

  return (
    <section id="achievements">
      <h2 className="section-title">Achievements & Recognition</h2>
      <div className="grid">
        {achievements.map((achievement, index) => (
          <div key={index} className="card" style={{ textAlign: 'center' }}>
            <div style={{ marginBottom: '1rem' }}>
              {achievement.icon}
            </div>
            <h3 style={{ color: '#ffffff', marginBottom: '0.5rem', fontSize: '1.25rem', fontWeight: '600' }}>{achievement.title}</h3>
            <p style={{ color: '#ffffff', fontWeight: '600', marginBottom: '0.5rem' }}>
              {achievement.event}
            </p>
            <p style={{ color: '#9ca3af', fontSize: '0.9rem', marginBottom: '1rem' }}>
              {achievement.year}
            </p>
            <p style={{ color: '#9ca3af', lineHeight: '1.6' }}>
              {achievement.description}
            </p>
          </div>
        ))}
      </div>
    </section>
  );
};

export default Achievements;